import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/Layout";
import { api } from "~/utils/api";
import { FiPlusSquare } from "react-icons/fi";
import { FadeLoader } from "react-spinners";

export default function Home() {
  const blogPostsQuery = api.blog.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Link href="/blog/new" className="fixed right-5 top-5">
          <FiPlusSquare size={35} />
        </Link>
        <p className="mt-10 text-3xl">Blogs by BRbase</p>
        {blogPostsQuery.isLoading && <FadeLoader color="white" />}
        {blogPostsQuery.isFetched && (
          <div className="my-10 grid grid-cols-1 gap-5">
            {blogPostsQuery.data?.map((blog, key) => (
              <Link
                className="from-top mx-5 rounded-md bg-[rgba(0,0,0,0.4)] p-5 text-white"
                style={{
                  animationDuration: `${key * 400}ms`,
                }}
                key={key}
                href={`blog/${blog.id}`}
              >
                <p>{blog.title}</p>
                <p>Created at {blog.createdAt.toLocaleDateString()}</p>
              </Link>
            ))}
          </div>
        )}
      </Layout>
    </>
  );
}
