import Head from "next/head";
import Link from "next/link";
import Layout from "~/components/Layout";
import { api } from "~/utils/api";
import { FiPlusSquare } from "react-icons/fi";

export default function Home() {
  const blogPosts = api.blog.getAll.useQuery().data;
  return (
    <>
      <Head>
        <title>Application Excercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Link href="/blog/new" className="fixed right-5 top-5">
          <FiPlusSquare size={35} />
        </Link>
        <p className="text-3xl mt-10">Blogs by BRbase</p>
        <div className="my-10 grid grid-cols-1 gap-5">
          {blogPosts?.map((blog, key) => (
            <Link
              className="rounded-md bg-[rgba(0,0,0,0.4)] p-5 text-white mx-5"
              key={key}
              href={`blog/${blog.id}`}
            >
              <p>{blog.title}</p>
              <p>Created at {blog.createdAt.toLocaleDateString()}</p>
            </Link>
          ))}
        </div>
      </Layout>
    </>
  );
}
